name: Push cloud-work image to Docker hub

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-work:latest
      -
        name: Deploy to GCP with App Engine
        run: python manage.py collectstatic
        run: docker-compose -f docker-compose-deploy.yml run --rm gcloud sh -c "gcloud app deploy --project blog-website-386414


